name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Update Aptitude.
        run: sudo apt-get update
      - name: Install Meson.
        run: sudo apt-get install -y meson ninja-build libnm-dev libglib2.0-dev
      - name: Initialise Meson.
        run: meson build
      - name: Run Ninja.
        run: ninja -C build
      - name: Perform static analysis.
        run: ninja -C build scan-build
