name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Update Aptitude.
        run: sudo apt-get update
      - name: Install Meson.
        run: sudo apt-get install -y meson
      - name: Install Ninja.
        run: sudo apt-get install -y ninja-build
      - name: Install libraries.
        run: sudo apt-get install -y libnm-dev libglib2.0-dev network-manager-dev
      - name: Install clang.
        run: sudo apt-get install -y clang-tools
      - name: Initialise Meson.
        run: meson build
      - name: Run Ninja.
        run: ninja -C build
      - name: Perform static analysis.
        run: ninja -C build scan-build
